### ISSUE TITLE
M8 - Google Map Display, Persistence and UML Sequence Diagram

### ISSUE THREAD

**Issue by cdecherd** [cdecherd/answertolife42#5]
- Create sequence diagrams for the application.
- Add the ability to show on a google map the locations of sightings
- Feature to filter out date range on rat sightings
- Add persistence into adding rat sighting data for project
- Added firebases

**Comment by jcnguyen1994** [comment]
-Created filter using arrayList and spinners
-Successfully filtered Google Map on Application
